### ISSUE TITLE
Maven package version number is truncated

### ISSUE THREAD

**Issue by meggima** [swisspush/apikana#181]
I want to implement publishing beta packages for our apikana generated NuGets, Mavens and Npms when building feature branches.

For NuGet and NPM we use the schema {semantic_version_number}-{branch-name}-{buildNr}

Example: 3.2.1-feature-new-field-2

When I tried to to this for Maven packages I noticed that part of the version name is cut and replaced.
The above example yields 3.2.1-feature-SNAPSHOT. This can result in non-unique maven packages and result in package conflicts.

The problem is the following line: https://github.com/swisspush/apikana/blob/592f18b98eb68a10078ea478ea40607aedcd316e/src/plopfile_start.js#L12

Two questions:

- what was the original idea behind the code referenced above?
- can we remove it?

**Comment by meggima** [comment]
cc @msallin

**Comment by lbovet** [comment]
The goal was to detect release candidates ".rc" and replace them with SNAPSHOT as it is the convention with maven.
Seems that the regexp is a bit too wide and captures non-rc stuff. We could refine it to capture only release candidates.
