### ISSUE TITLE
DateOnly data example is not compatible to RFC 3339, section 5.6

### ISSUE THREAD

**Issue by jarosmpost** [swisspush/apikana#190]
DateOnly is not compliant with RFC 3339, section 5.6, because the time zone is missing. It is not clear at what moment the change from one day to another happens.

**Comment by hiddenalpha** [comment]
Works perfectly fine here when using generated **Java** classes:

![grafik](https://user-images.githubusercontent.com/23085769/150801338-d4cf8f63-e889-404f-884f-979771ab1a12.png)

Maybe only affect .Net stuff?

**Comment by jarosmpost** [comment]
From https://github.com/swisspush/apikana/blob/develop/src/model/ts/default-types.ts:

`/**`
` * <a href="https://swagger.io/docs/specification/data-models/data-types/#string">String @format date</a>,`
` * as defined by <a href="https://tools.ietf.org/html/rfc3339#section-5.6">RFC 3339, section 5.6</a>,`
` * for example: <code>2017-07-21</code>.`
` */`
`export type DateOnly=string // @format date`

The example is only 'yyyy-mm-dd' without time zone and this not compatible to RFC 3339, section 5.6.

**Comment by hiddenalpha** [comment]
Ah :) I missed that. We've a DateOnly not a DateTime as I thought.

Unluckily I guess the situation gets a bit trickier I think :|

Originally "*DateOnly*" was **clearly** defined to be the "*full-date*" part named in the linked spec. (See [older default-types.ts](https://github.com/swisspush/apikana/blob/v0.7.5/src/model/ts/default-types.ts#L15-L21)). This way, the format "*YYYY-mm-dd*" even is the only valid format. As its definition was unmistakable (cited from RFC):
```
   full-date       = date-fullyear "-" date-month "-" date-mday
   date-fullyear   = 4DIGIT
   date-month      = 2DIGIT  ; 01-12
   date-mday       = 2DIGIT  ; 01-28, 01-29, 01-30, 01-31 based on
                             ; month/year
```
As we can see there's neither timezone nor offset information in this "*full-date*" type. I've no idea why this detail got dropped from Apikana doc somewhen later.

---
Nevertheless I think the remaining question is: What is the correct way to store a DateOnly but including offset information. Actually I don't know such a format.

We usually only use "*DateTime*" even we're not interested in the time part. This might be the reason we never stumbled about this yet.

**Comment by lbovet** [comment]
DateOnly is precisely meant to refer to a date and not a point in time (datetime). The timezone is irrelevant.
It is not intended to be deserialized as a datetime but as a date. E.g. java.time.LoclalDate in Java.

**Comment by jarosmpost** [comment]
@lbovet : Okay. That's a good clue. I make a suggestion to improve the comment for DateOnly: https://github.com/swisspush/apikana/pull/191.
