### ISSUE TITLE
References to definitions not resolved when using complete-api.yaml/json

### ISSUE THREAD

**Issue by meggima** [swisspush/apikana#198]
When I use the generated `complete-api.yaml` or `complete-api.json` in Swagger 2.X, references in subobjects are not resolved and show up as text like `#/definitions/ReferencedTypeName`.

See the following [example](https://techsysapi.github.io/parcel-coding-stream-api-dist/v4.1.0/ui/?url=../complete-api.yaml#!/Kafka/get_logistics_parcel_coding_final_Mailpiece_event).

When replacing `#/definitions/ReferencedTypeName` with `ReferencedTypeName` it works.

The generated schema works against latest Swagger version, but shows some warnings and errors in [Swagger Editor](https://editor.swagger.io/)

I noticed that the `complete-api.yaml` generated using older version 0.9.21 looks entirely different and subreferences are resolved as desired. The generation with version 0.9.22 and later versions has that flaw described above.

**Comment by lbovet** [comment]
Actually, the references are correct with the path (e.g. #/definitions/ReferencedTypeName). They were incorrect without it, from an openapi point of view. We have to fix the rendering when references have a path.
