### ISSUE TITLE
JSON Schema export contains required field with empty array

### ISSUE THREAD

**Issue by pazoozooCH** [swisspush/apikana#26]
For an object that doesn't have any required properties, the output JSON Schema (v4) includes a required field with an empty array: `"required": []`

According to the JSON Schema specification, this is not valid and will result in validation errors when parsed: https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.4.3: _The value of this keyword MUST be an array.  This array MUST have at least one element._

**Comment by lbovet** [comment]
I assigned to Martin. Do it if you have time, otherwise please comment and we assign to someone other.

**Comment by pazoozooCH** [comment]
@lbovet , could you have a look at #27 ? Travis build fails, but it doesn't seem to be related to my changes - it already failed for to the previous PR #25 ...

Will it automatically create and deploy the new version to the NPM repo?
