### ISSUE TITLE
Chrome does not like XHR in main thread

### ISSUE THREAD

**Issue by lbovet** [swisspush/apikana#28]
We can see this warning in the console:

`browserify.js:131919 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`

In fact, in associations with CORS headers, this activates a bug in Chrome preventing certain URLs to be fetched using sync XHR like the .ts files.
The solution is to move the generation code into a web worker.

**Comment by hiddenalpha** [comment]
Seems fixed. Should we close this issue?
